services:
  - type: web
    name: studytrack-backend
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/studytrack-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studytrack-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: studytrack-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: studytrack-db
          property: password
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: studytrack-db
    databaseName: studytrack_db
    user: studytrack_user 